#!/usr/bin/env bash
# Renders Formula/mobs.rb with the sha256 of each release asset and pushes it
# to the mobdotso/homebrew-tap repository.
#
# Usage: scripts/update-tap.sh <version>
# Requires: GITHUB_TOKEN (or TAP_GITHUB_TOKEN) with push access to the tap.

set -euo pipefail

VERSION="${1:?usage: update-tap.sh <version>}"
TOKEN="${TAP_GITHUB_TOKEN:-${GITHUB_TOKEN:?set TAP_GITHUB_TOKEN or GITHUB_TOKEN}}"
BASE="https://github.com/mobdotso/cli/releases/download/v${VERSION}"
TAP_REPO="mobdotso/homebrew-tap"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

sha_for() {
  target="$1"
  curl -fsSL "${BASE}/mobs-v${VERSION}-${target}.tar.gz" -o "${workdir}/${target}.tar.gz"
  shasum -a 256 "${workdir}/${target}.tar.gz" 2>/dev/null | cut -d' ' -f1 \
    || sha256sum "${workdir}/${target}.tar.gz" | cut -d' ' -f1
}

echo "Computing release asset checksums for v${VERSION}"
SHA_MAC_ARM="$(sha_for aarch64-apple-darwin)"
SHA_MAC_X64="$(sha_for x86_64-apple-darwin)"
SHA_LINUX_ARM="$(sha_for aarch64-unknown-linux-musl)"
SHA_LINUX_X64="$(sha_for x86_64-unknown-linux-musl)"

cat > "${workdir}/mobs.rb" <<FORMULA
# Generated by mobdotso/cli scripts/update-tap.sh for v${VERSION}.
class Mobs < Formula
  desc "Command line client for the mob.so API"
  homepage "https://github.com/mobdotso/cli"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mobdotso/cli/releases/download/v#{version}/mobs-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_ARM}"
    end
    on_intel do
      url "https://github.com/mobdotso/cli/releases/download/v#{version}/mobs-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_X64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mobdotso/cli/releases/download/v#{version}/mobs-v#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "https://github.com/mobdotso/cli/releases/download/v#{version}/mobs-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_X64}"
    end
  end

  def install
    bin.install "mobs"
  end

  test do
    assert_match "mobs", shell_output("#{bin}/mobs --version")
  end
end
FORMULA

echo "Pushing Formula/mobs.rb to ${TAP_REPO}"
git clone --depth 1 "https://x-access-token:${TOKEN}@github.com/${TAP_REPO}.git" "${workdir}/tap"
mkdir -p "${workdir}/tap/Formula"
cp "${workdir}/mobs.rb" "${workdir}/tap/Formula/mobs.rb"
cd "${workdir}/tap"
git config user.name "mobs-release-bot"
git config user.email "release@mob.so"
git add Formula/mobs.rb
if git diff --cached --quiet; then
  echo "Formula unchanged; nothing to push"
  exit 0
fi
git commit -m "mobs ${VERSION}"
git push origin HEAD
echo "Tap updated to ${VERSION}"
